### ISSUE TITLE
No preview downloaded/generated (at least in v11.5.9)

### ISSUE THREAD

**Issue by ochorocho** [ayacoo/tiktok#3]
Hey, just tried the extension to see if it works with the [online-media-updater](https://github.com/b13/online-media-updater) 
But there was no thumbnail generated.

<img width="253" alt="Bildschirmfoto 2022-07-26 um 20 22 46" src="https://user-images.githubusercontent.com/4623070/181087563-4a3ee44a-be21-4888-a1b5-d94f7781744a.png">

**Comment by ayacoo** [comment]
@ochorocho Do you maybe have the Tiktok link for me? I had also tried 1-2 videos yesterday and in the 11er TYPO3 ran everything so far okay.

Which TYPO3 version do you use?

**Comment by ochorocho** [comment]
TYPO3 v11.5.9

The tested links:

* https://www.tiktok.com/@kaby.llane/video/7124002602576055557
* https://www.tiktok.com/@ez_yunusemre/video/7124428298209332486?is_copy_url=1&is_from_webapp=v1
* https://www.tiktok.com/@chinesedelicious22/video/7105225855470685482?is_copy_url=1&is_from_webapp=v1

**Comment by ayacoo** [comment]
I can't explain that yet. Which way did you use to add the URL? (Filelist oder via content element?)
Can you please check in the sys_file_metadata if all tiktok_* fields are filled?

Finally the code only uses the TYPO3 method to load the image: 
`$previewImage = GeneralUtility::getUrl($previewImageUrl);`

**Comment by ochorocho** [comment]
🤦  ... the fields were missing. Sorry for the noise!
Works as expected now. Event the online-media-updater does it's job.
