### ISSUE TITLE
Extension in TYPO3 11.5 results in error, if file is added via fileslist

### ISSUE THREAD

**Issue by PLACEBOBRO** [ayacoo/tiktok#9]
If I want to add a TikTok video via fileslist using the URL, it results in the following error:

![Bildschirm­foto 2023-04-04 um 11 22 14](https://user-images.githubusercontent.com/40799248/229747782-c6238835-b59e-40db-9048-215698eab00d.png)

The used TikTok link was:
https://www.tiktok.com/@umihito/video/7217355553817857285?lang=de-DE
Also without the URL-parameter '?lang=de-DE', the error is showing up

**System:** TYPO3 11.5.23, PHP 7.4
**Extension Version:** 1.0.0

**Comment by ayacoo** [comment]
Thanks for your feedback! I reproduced it once locally and got this message:

`PHP Warning: rename(/var/www/html/var/transient/online_mediacxTNvS,/var/www/html/public/fileadmin/tiktok/_werbung__heute_machen_wir_mit_der_kchenmaschine_von_@boschhomede_einen_leckeren_karottenkuchen_mit_selbstgemachten_marzipan-karotten_als_dekor__seit_rund_zwei_jahren_gibt_es_keinen_tag__an_dem_ich_meine_kchenmaschine_von_bosch_nicht_nutze._sowohl_im_allt.tiktok): File name too long in /var/www/html/public/typo3/sysext/core/Classes/Resource/Driver/LocalDriver.php line 803`

I'll take care of a bugfix release and then you can test it again.

**Comment by ayacoo** [comment]
@PLACEBOBRO I played out a new version that limits the file name to 100 characters. Please see if this helps you with your problem.

**Comment by PLACEBOBRO** [comment]
I've tested out a few links with longer descriptions.
Looks like it's working! 🚀 
Thank you for the quick fix!
